name: .NET Core

on:
  push:
    branches: [ main ]
    paths: 'CodersAcademy/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore CodersAcademy/CodersAcademy.sln
    - name: Build
      run: dotnet build CodersAcademy/CodersAcademy.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test CodersAcademy/CodersAcademy.sln --no-restore --verbosity normal
